# Site settings
title: Rules for Robots
email: greg@webstop.com
description: A blog about web design, programming, and other geeky things.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rulesforrobots.com" # the base hostname & protocol for your site
twitter_username: Agent_G
github_username:  hemphill

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    line_numbers: true
sass:
  style: :compressed
